<?php


namespace App\Admin\Http\Sections\news;
use App\Models\news\News;
use Illuminate\Support\Facades\Log;

use AdminColumn;
use AdminDisplay;
use AdminForm;
use AdminFormElement;
use AdminDisplayFilter;
use AdminSection;
use AdminColumnFilter;

use SleepingOwl\Admin\Contracts\Display\DisplayInterface;
use SleepingOwl\Admin\Contracts\Form\FormInterface;
use SleepingOwl\Admin\Contracts\Initializable;
use SleepingOwl\Admin\Form\Buttons\Cancel;
use SleepingOwl\Admin\Form\Buttons\Save;
use SleepingOwl\Admin\Form\Buttons\SaveAndClose;
use SleepingOwl\Admin\Form\Buttons\SaveAndCreate;
use SleepingOwl\Admin\Display\Column\Order;
use SleepingOwl\Admin\Display\Tree\OrderTreeType;
use SleepingOwl\Admin\Display\Tree\KalnoyNestedsetType;
use SleepingOwl\Admin\Navigation\Badge;
use SleepingOwl\Admin\Section;

class SNews extends Section implements Initializable
{
    /**
     * @see http://sleepingowladmin.ru/docs/model_configuration#ограничение-прав-доступа
     *
     * @var bool
     */
    protected $checkAccess = false;

    /**
     * @var string
     */
    protected $title = 'Новости';

    /**
     * @var string
     */
    protected $alias;

    const PUBLIC_IMAGES_UPLOAD_PATH = 'img/page';

    /**
     * Initialize class.
     */
    public function initialize()
    {
        //$this->addToNavigation()->setIcon('fa fa-sitemap')->setBadge(new Badge('New'));
    }

    public function isDisplayable() {
        return true;
    }

    /**
     * @return DisplayInterface
     */
    public function onDisplay($scopes = []) {
        $display = AdminDisplay::datatables()
            ->setName('firstdatatables')
            ->setOrder([[0, 'asc']])
            ->setDisplaySearch(true)
            ->paginate(10)
            ->setHtmlAttribute('class', 'table-primary table-hover th-left');

        $display->getFilters()->initialize();

        if($scopes){
            $display->getScopes()->push($scopes);
        }

        $filterColumns = [
            AdminColumnFilter::select()
                ->setModelForOptions(News::class, 'lang')
                ->setLoadOptionsQueryPreparer(function ($element, $query) {
                    return $query;
                })
                ->setDisplay('lang')
                ->setColumnName('lang')
                ->setWidth(700)
                ->setPlaceholder('All news')
            ,
        ];

        $display->setColumnFilters($filterColumns);
        $display->getColumnFilters()->setPlacement('card.heading');

        $columns = [
            AdminColumn::text('id', '#')->setWidth('50px')
                ->setHtmlAttribute('class', 'text-center'),
            AdminColumn::text('name', 'Имя'),
            AdminColumn::text('lang', 'Язык')
                ->setSearchCallback(function ($column, $query, $search) {
                return $query
                    ->orWhere('lang', 'like', '%' . $search . '%')
                    ->orWhere('created_at', 'like', '%' . $search . '%');
            })
                ->setOrderable(function ($query, $direction) {
                    $query->orderBy('lang', $direction);
                }),

            AdminColumn::text('slug', 'url'),

            AdminColumn::text('created_at', 'Created / updated', 'updated_at')
                ->setWidth('160px')
                ->setOrderable(function ($query, $direction) {
                    $query->orderBy('created_at', $direction);
                })
                ->setSearchable(false)
        ];

        $display->setColumns($columns);

        return $display;
    }

    public function fireEdit($id, $payload = []) {
        return parent::fireEdit($id, $payload); // TODO: Change the autogenerated stub
    }

    /**
     * Создание таба Анонс новости
     * @param $lang
     * @return \SleepingOwl\Admin\Form\Columns\Columns
     * @throws \Exception
     */
    public function genFieldsAnons (){
        return
            AdminFormElement::columns()
                ->addColumn([
                    AdminFormElement::ckeditor('data->announce->text', 'Текст'),
                ], 12)
                ->addColumn([
                    AdminFormElement::image('data->announce->image','Фотография')
                        ->setUploadPath(function(\Illuminate\Http\UploadedFile $file) {
                            return 'img/page'; // public/files
                        })->mutateValue(function($value) {
                            if(str_starts_with($value, self::PUBLIC_IMAGES_UPLOAD_PATH)) {
                                $value = '/'.$value;
                            }
                            return $value;
                        }),
                ], 6);
    }

    /**
     * Создание таба наполнения новости
     * @param $lang
     * @return \SleepingOwl\Admin\Form\Columns\Columns
     * @throws \Exception
     */
    public function genFieldsNews (){
        return
            AdminFormElement::columns()
                ->addColumn([
                    AdminFormElement::text('data->main->title', 'Заголовок')->required()
                ], 12)
                ->addColumn([
                    AdminFormElement::text('data->main->subtitle', 'Подзаголовок'),
                ], 12)
                ->addColumn([
                    AdminFormElement::ckeditor('data->main->textNews', 'Текст'),
                ], 12)
                ->addColumn([
                    AdminFormElement::image('data->main->image','Image')
                        ->setUploadPath(function(\Illuminate\Http\UploadedFile $file) {
                            return 'img/page';
                        })->mutateValue(function($value) {
                            if(str_starts_with($value, self::PUBLIC_IMAGES_UPLOAD_PATH)) {
                                $value = '/'.$value;
                            }
                            return $value;
                        })
                ], 'col-12 col-sm-6 col-md-6 col-lg-3');
    }


    /**
     * @param int|null $id
     * @return FormInterface
     */
    public function onEdit($id) {
        $langList = config('onessa5.adminLanguages');
        $form = AdminForm::card();
        $dataHeader = [
            AdminFormElement::columns()
                ->addColumn([
                    AdminFormElement::text('name', 'Name')->required()
                ], 3)
                ->addColumn([
                    AdminFormElement::text('slug', 'Slug')->required(),
                ], 3)
                ->addColumn([
                    AdminFormElement::select('lang', 'Язык', $langList)->required(),
                ], 3)
                ->addColumn([
                    AdminFormElement::date('news_date', 'Дата новости')->required()
                ], 3)
                ->addColumn([
                    AdminFormElement::checkbox('is_active', 'Активно'),
                ], 3)
        ];

        $dataTabsBody =[];

        $anonsTab = new \SleepingOwl\Admin\Form\FormElements([$this->genFieldsAnons()]);

        $newsTab = new \SleepingOwl\Admin\Form\FormElements([$this->genFieldsNews()]);

            $dataTabsBody['News'] = new \SleepingOwl\Admin\Form\FormElements([
                AdminDisplay::tabbed([
                    'Анонс' => $anonsTab,
                    'Новость' => $newsTab,
                ])
            ]);

        // Config
        $dataTabsBody['Config'] = new \SleepingOwl\Admin\Form\FormElements([
            AdminFormElement::columns()
                ->addColumn([
                    AdminFormElement::text('data_config->model', 'Model')
                        ->setHelpText('Имя класса модели')
                ], 4)
                ->addColumn([
                    AdminFormElement::text('data_config->form', 'Form')
                        ->setHelpText('Имя класса для модификации формы')
                ], 4)
                ->addColumn([
                    AdminFormElement::text('data_config->view', 'View')
                        ->setHelpText('Имя view')
                ], 4)
                ->addColumn([
                    AdminFormElement::text('data_config->convertor', 'Convertor')
                        ->setHelpText('Функция контроллера в которая будет вызвана для преобразования данных')
                ], 4),

            AdminFormElement::columns()
                ->addColumn([
                    AdminFormElement::text('created_at', 'Создано')->setReadonly(true),
                    AdminFormElement::text('created_by', 'Создал')->setReadonly(true)
                ], 4)->addColumn([
                    AdminFormElement::text('updated_at', 'Изменено')->setReadonly(true),
                    AdminFormElement::text('updated_by', 'Изменил')->setReadonly(true)
                ], 4)->addColumn([
                    AdminFormElement::text('deleted_at', 'Удалено')->setReadonly(true),
                    AdminFormElement::text('deleted_by', 'Удалил')->setReadonly(true)
                ])
        ]);

        $dataFooter = [

        ];

        /*
        Расширяем форму через получение элементов из описания конфига
        Проходимся по списку классов. У каждого класса получаем элементы формы
        если это новый таб - добавляем таб, если существующий -добавляем элементы в существующий
        */
        $extensionEdit = $this->getExtension();

        foreach ($extensionEdit as $extensionSectionKey => $extensionObj) {

            switch ($extensionSectionKey) {
                case 'header':
                    $dataHeader = array_merge($dataHeader, $extensionObj);
                    break;
                case 'body':
                    foreach ($extensionObj as $extensionTabKey => $extensionElements) {

                        if (array_key_exists($extensionTabKey, $dataTabsBody)) {

                            $dataTabsBody[$extensionTabKey]->addElement($extensionElements);
                        } else {
                            $dataTabsBody[$extensionTabKey] = $extensionElements;
                        }
                    }
                    break;
                case 'footer':
                    $dataFooter = array_merge($dataFooter, $extensionObj);
                    break;
            }
        }

        $dataBody = AdminDisplay::tabbed($dataTabsBody);

        $form->addHeader($dataHeader);
        $form->addBody($dataBody);
        $form->addBody($dataFooter);
        $form->getButtons()->setButtons([
            'save' => new Save(),
            'save_and_close' => new SaveAndClose(),
            'save_and_create' => new SaveAndCreate(),
            'cancel' => (new Cancel()),
        ]);


        return $form;
    }

    public function isCreatable() {
        return true;
    }

    /**
     * @param array $payload
     * @return FormInterface
     */
    public function onCreate($payload = []) {
        return $this->onEdit(null);
    }

    /**
     * @return void
     */
    public function onDelete($id) {
        // todo: remove if unused
    }

    /**
     * @return void
     */
    public function onRestore($id) {
        // todo: remove if unused
    }

    /**
     * Получение расширения для формы и установка модели
     * @return array
     */
    public function getExtension(): array
    {
        $extForm = [];
        $modelValue = $this->getModelValue();

        try {
            $model = $this->getModel();

            if (null !== $modelValue) {
                // Получаем имя класса для расширения полей секции
                $sectionClassName = $modelValue->form;

                /**
                 * @var \Onessa5\Core\Admin\Http\Sections\ISectionExt
                 */
                $sectionExtClass = (!empty($sectionClassName)) ? new $sectionClassName() : null;

                if (null !== $sectionExtClass) {
                    $sectionExtClass::modifyModel($model);
                    // получение расширения формы
                    $extForm = $sectionExtClass->getEdit($model);
                }
            }
        } catch (\Exception $exception) {
            Log::error($exception->getMessage());
        }

        return $extForm;
    }

}
